// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sirena.Api.Data;

#nullable disable

namespace Sirena.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819210039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sirena.Api.Domain.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_session_created");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_messages_role", "role in ('user', 'assistant')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.ChatSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("age");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("SkinProfile")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("skin_profile");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_chat_sessions_created_at");

                    b.ToTable("chat_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_sessions_age", "age between 13 and 99");

                            t.HasCheckConstraint("ck_chat_sessions_skin_profile", "skin_profile in ('seca', 'grasa', 'mixta', 'sensible', 'normal')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_name");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("delivery_address");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("delivery_fee");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_status_created_at");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_amounts", "subtotal >= 0 and delivery_fee >= 0 and total >= 0");

                            t.HasCheckConstraint("ck_orders_location", "(latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180)");

                            t.HasCheckConstraint("ck_orders_status", "status in ('pending', 'confirmed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_order_items_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("collection");

                    b.Property<string[]>("Concerns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("concerns");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("image_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("role");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_url");

                    b.Property<string[]>("SuitableFor")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("suitable_for");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usage");

                    b.HasKey("Id");

                    b.HasIndex("Collection")
                        .HasDatabaseName("ix_products_collection");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_products_role");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_collection", "collection in ('esentis', 'makeup')");

                            t.HasCheckConstraint("ck_products_price", "price >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Collection = "esentis",
                            Concerns = new[] { "limpieza", "impurezas" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Gel facial de uso diario que elimina impurezas y deja la piel fresca y limpia.",
                            ImagePath = "/products/gel-facial.webp",
                            Name = "Gel Facial Esentis Limpiador 200 Ml",
                            Price = 275m,
                            Role = "Limpieza",
                            SourceUrl = "https://www.sirena.do/esentis-gel-facial-limpiador-200-ml-2123816/p",
                            SuitableFor = new[] { "seca", "grasa", "mixta", "sensible", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Usar como primer paso sobre el rostro húmedo y retirar con agua."
                        },
                        new
                        {
                            Id = 2L,
                            Collection = "esentis",
                            Concerns = new[] { "manchas", "tono desigual", "luminosidad" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sérum ligero orientado a unificar el tono y reducir la apariencia de manchas visibles.",
                            ImagePath = "/products/serum-aclarante.webp",
                            Name = "Serum Aclarante Esentis 30 Ml",
                            Price = 495m,
                            Role = "Tratamiento",
                            SourceUrl = "https://www.sirena.do/esentis-serum-aclarante-30-ml-2124025/p",
                            SuitableFor = new[] { "grasa", "mixta", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar pocas gotas después de limpiar y antes de la crema; de día complementar con protector solar."
                        },
                        new
                        {
                            Id = 3L,
                            Collection = "esentis",
                            Concerns = new[] { "cabello seco", "nutrición capilar" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Crema de peinar sin enjuague para cabello normal a seco.",
                            ImagePath = "/products/leave-in.webp",
                            Name = "Leave-In Esentis Nutricion 300 Ml",
                            Price = 325m,
                            Role = "Cabello",
                            SourceUrl = "https://www.sirena.do/esentis-leave-in-nutricion-300-ml-2123807/p",
                            SuitableFor = new[] { "seca", "grasa", "mixta", "sensible", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Distribuir en el cabello húmedo, de medios a puntas, sin enjuagar."
                        },
                        new
                        {
                            Id = 4L,
                            Collection = "esentis",
                            Concerns = new[] { "líneas finas", "firmeza", "luminosidad" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sérum orientado a líneas de expresión, hidratación, firmeza y luminosidad.",
                            ImagePath = "/products/serum-antiedad.webp",
                            Name = "Serum Esentis Anti Edad 30 Ml",
                            Price = 495m,
                            Role = "Tratamiento",
                            SourceUrl = "https://www.sirena.do/esentis-serum-anti-edad-30-ml-2124019/p",
                            SuitableFor = new[] { "seca", "normal", "mixta" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar pocas gotas después de limpiar y antes de la crema."
                        },
                        new
                        {
                            Id = 5L,
                            Collection = "esentis",
                            Concerns = new[] { "ojeras", "líneas finas", "fatiga" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Contorno ligero orientado a líneas finas, ojeras y signos de fatiga.",
                            ImagePath = "/products/contorno-antiedad.webp",
                            Name = "Contorno De Ojo Antiedad Esentis 15 Ml",
                            Price = 400m,
                            Role = "Contorno de ojos",
                            SourceUrl = "https://www.sirena.do/esentis-contorno-de-ojo-antiedad-15-ml-2124023/p",
                            SuitableFor = new[] { "seca", "normal", "mixta" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar poca cantidad con toques suaves sobre el hueso orbital."
                        },
                        new
                        {
                            Id = 6L,
                            Collection = "esentis",
                            Concerns = new[] { "manchas", "hidratación", "tono desigual" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Crema orientada a disminuir la apariencia de manchas, unificar el tono e hidratar.",
                            ImagePath = "/products/crema-aclarante.webp",
                            Name = "Crema Aclarante Esentis 50 Ml",
                            Price = 450m,
                            Role = "Hidratación",
                            SourceUrl = "https://www.sirena.do/esentis-crema-aclarante-50-ml-2124027/p",
                            SuitableFor = new[] { "seca", "normal", "mixta" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar después del sérum y terminar con protector solar durante el día."
                        },
                        new
                        {
                            Id = 7L,
                            Collection = "esentis",
                            Concerns = new[] { "sequedad", "ojeras", "fatiga" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Contorno que hidrata y suaviza el área de los ojos.",
                            ImagePath = "/products/contorno-hidratante.webp",
                            Name = "Contorno De Ojo Hidratante Esentis 15 Ml",
                            Price = 400m,
                            Role = "Contorno de ojos",
                            SourceUrl = "https://www.sirena.do/esentis-contorno-de-ojo-hidratante-15-ml-2124035/p",
                            SuitableFor = new[] { "seca", "sensible", "normal", "mixta" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar poca cantidad con el dedo anular y toques suaves."
                        },
                        new
                        {
                            Id = 8L,
                            Collection = "esentis",
                            Concerns = new[] { "grasa", "brillo", "sebo", "zona t" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Producto orientado a equilibrar el sebo y reducir brillo y sensación grasa.",
                            ImagePath = "/products/sebo-regular.webp",
                            Name = "Sebo Regular Esentis 50 Ml",
                            Price = 575m,
                            Role = "Balance",
                            SourceUrl = "https://www.sirena.do/esentis-sebo-regular-50-ml-2124039/p",
                            SuitableFor = new[] { "grasa", "mixta" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar una capa ligera después de limpiar, principalmente en zonas con brillo."
                        },
                        new
                        {
                            Id = 9L,
                            Collection = "makeup",
                            Concerns = new[] { "base", "cobertura", "tono" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Base líquida con cobertura ligera a media y acabado natural radiante.",
                            ImagePath = "/products/makeup/base-almay.webp",
                            Name = "Base Facial Líquida Always Neutral",
                            Price = 1400m,
                            Role = "Base",
                            SourceUrl = "https://www.sirena.do/almay-clear-complexion-makeup-neutral-1747245/p",
                            SuitableFor = new[] { "seca", "grasa", "mixta", "sensible", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Probar el tono en la mandíbula y difuminar desde el centro hacia afuera."
                        },
                        new
                        {
                            Id = 10L,
                            Collection = "makeup",
                            Concerns = new[] { "rubor", "mejillas", "color" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rubor compacto de textura sedosa y acabado natural luminoso.",
                            ImagePath = "/products/makeup/rubor-she.webp",
                            Name = "Polvo de Rubor S.HE R.Bs998",
                            Price = 138m,
                            Role = "Rubor",
                            SourceUrl = "https://www.sirena.do/s-he-blush-powder-r-bs998-2140832/p",
                            SuitableFor = new[] { "seca", "grasa", "mixta", "sensible", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar poca cantidad sobre las mejillas y difuminar gradualmente."
                        },
                        new
                        {
                            Id = 11L,
                            Collection = "makeup",
                            Concerns = new[] { "labial", "gloss", "labios" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Brillo labial Wet N Wild de la línea MegaSlicks en tono Love.",
                            ImagePath = "/products/makeup/labial-wetnwild.webp",
                            Name = "Labial Wet N Wild Mega Sliks Gloss Love",
                            Price = 475m,
                            Role = "Labial",
                            SourceUrl = "https://www.sirena.do/wet-n-wild-mega-sliks-lip-gloss-love-lg-2007202/p",
                            SuitableFor = new[] { "seca", "grasa", "mixta", "sensible", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar directamente y reaplicar según el acabado deseado."
                        },
                        new
                        {
                            Id = 12L,
                            Collection = "makeup",
                            Concerns = new[] { "corrector", "ojeras", "imperfecciones" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Corrector cremoso tono Honey para disimular visualmente ojeras e imperfecciones.",
                            ImagePath = "/products/makeup/corrector-amuse.webp",
                            Name = "Corrector Amuse Full Honey",
                            Price = 265.30m,
                            Role = "Corrector",
                            SourceUrl = "https://www.sirena.do/amuse-full-concealer-honey-kl237-mix-6-1973074/p",
                            SuitableFor = new[] { "seca", "grasa", "mixta", "sensible", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar pequeñas cantidades y difuminar sin arrastrar la piel."
                        },
                        new
                        {
                            Id = 13L,
                            Collection = "makeup",
                            Concerns = new[] { "prebase", "poros", "textura" },
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Prebase facial para preparar visualmente la superficie antes del maquillaje.",
                            ImagePath = "/products/makeup/prebase-sky.webp",
                            Name = "Pre-base Sky Smooth & Poreless",
                            Price = 281.25m,
                            Role = "Prebase",
                            SourceUrl = "https://www.sirena.do/sky-primer-smooth-poreless-1882109/p",
                            SuitableFor = new[] { "seca", "grasa", "mixta", "sensible", "normal" },
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Usage = "Aplicar una capa fina después del cuidado facial y antes de la base."
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.SkinAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("ColorimetryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("colorimetry_json");

                    b.Property<short>("Confidence")
                        .HasColumnType("smallint")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_json");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("skin_type");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("ix_skin_analyses_chat_session_id");

                    b.ToTable("skin_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_skin_analyses_score", "overall_score between 0 and 100 and confidence between 0 and 100");

                            t.HasCheckConstraint("ck_skin_analyses_type", "skin_type in ('seca', 'grasa', 'mixta', 'sensible', 'normal')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.ChatMessage", b =>
                {
                    b.HasOne("Sirena.Api.Domain.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Sirena.Api.Domain.OrderItem", b =>
                {
                    b.HasOne("Sirena.Api.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sirena.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sirena.Api.Domain.SkinAnalysis", b =>
                {
                    b.HasOne("Sirena.Api.Domain.ChatSession", "ChatSession")
                        .WithMany("SkinAnalyses")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Sirena.Api.Domain.ChatSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("SkinAnalyses");
                });

            modelBuilder.Entity("Sirena.Api.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
