// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sirena.Api.Data;

#nullable disable

namespace Sirena.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260819220324_UseOfficialCatalog")]
    partial class UseOfficialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sirena.Api.Domain.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_session_created");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_messages_role", "role in ('user', 'assistant')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.ChatSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("age");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("SkinProfile")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("skin_profile");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_chat_sessions_created_at");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_chat_sessions_slug");

                    b.ToTable("chat_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_sessions_age", "age between 13 and 99");

                            t.HasCheckConstraint("ck_chat_sessions_skin_profile", "skin_profile is null or skin_profile in ('seca', 'grasa', 'mixta', 'sensible', 'normal')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_name");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("delivery_address");

                    b.Property<decimal>("DeliveryFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("delivery_fee");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_orders_status_created_at");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_amounts", "subtotal >= 0 and delivery_fee >= 0 and total >= 0");

                            t.HasCheckConstraint("ck_orders_location", "(latitude is null and longitude is null) or (latitude between -90 and 90 and longitude between -180 and 180)");

                            t.HasCheckConstraint("ck_orders_status", "status in ('pending', 'confirmed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.ToTable("order_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_items_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_order_items_unit_price", "unit_price >= 0");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("collection");

                    b.Property<string[]>("Concerns")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("concerns");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("role");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("source_url");

                    b.Property<string[]>("SuitableFor")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("suitable_for");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usage");

                    b.HasKey("Id");

                    b.HasIndex("Collection")
                        .HasDatabaseName("ix_products_collection");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_products_role");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_collection", "collection in ('esentis', 'makeup')");

                            t.HasCheckConstraint("ck_products_price", "price >= 0");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.SkinAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChatSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_session_id");

                    b.Property<string>("ColorimetryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("colorimetry_json");

                    b.Property<short>("Confidence")
                        .HasColumnType("smallint")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metrics_json");

                    b.Property<short>("OverallScore")
                        .HasColumnType("smallint")
                        .HasColumnName("overall_score");

                    b.Property<string>("SkinType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("skin_type");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId")
                        .HasDatabaseName("ix_skin_analyses_chat_session_id");

                    b.ToTable("skin_analyses", null, t =>
                        {
                            t.HasCheckConstraint("ck_skin_analyses_score", "overall_score between 0 and 100 and confidence between 0 and 100");

                            t.HasCheckConstraint("ck_skin_analyses_type", "skin_type in ('seca', 'grasa', 'mixta', 'sensible', 'normal')");
                        });
                });

            modelBuilder.Entity("Sirena.Api.Domain.ChatMessage", b =>
                {
                    b.HasOne("Sirena.Api.Domain.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Sirena.Api.Domain.OrderItem", b =>
                {
                    b.HasOne("Sirena.Api.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sirena.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Sirena.Api.Domain.SkinAnalysis", b =>
                {
                    b.HasOne("Sirena.Api.Domain.ChatSession", "ChatSession")
                        .WithMany("SkinAnalyses")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("Sirena.Api.Domain.ChatSession", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("SkinAnalyses");
                });

            modelBuilder.Entity("Sirena.Api.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
